#!/usr/bin/env bash

trap "" SIGINT
while true; do
	read -erp "VS Server> " input
	case "$input" in
		"exit"|"shutdown")
			echo "Shutting down the server"
			echo "exit" > "$STATUS_FILE"
			tmux send-keys -t "$SESSION_NAME:Manager.0" "^C" ENTER
		;;
		"restart")
			echo "restart" > "$STATUS_FILE"
			tmux send-keys -t "$SESSION_NAME:Manager.0" "^C" ENTER
		;;
		"clear")
			clear;;
		"killserver")
			rm "$STATUS_FILE"
			tmux kill-session -t "$SESSION_NAME"
		;;
		"test")
			echo "$SESSION_NAME";;
		"nah") bash;;
		*)
			tmux send-keys -t "$SESSION_NAME:Manager.0" "/$input" ENTER;;
	esac
	history -s $input
done
