#!/usr/bin/env bash

trap "" SIGINT
while true; do
	read -erp "VS Server> " input
	case "$input" in
		"exit"|"shutdown")
			echo "[vss-tmux] Shutting down the server"
			echo "exit" > "$STATUS_FILE"
			tmux send-keys -t "$SESSION_NAME:Manager.0" "^C" ENTER
		;;
		"restart")
			echo "restart" > "$STATUS_FILE"
			tmux send-keys -t "$SESSION_NAME:Manager.0" "^C" ENTER
		;;
		"playit-restart"|"restart-playit")
		    echo "[vss-tmux] Restarting playit"
		    tmux send-keys -t "$SESSION_NAME":playit "^C" ENTER
		    tmux send-keys -t "$SESSION_NAME":playit "playit" ENTER
		;;
		"clear")
			clear;;
		"killserver")
			rm "$STATUS_FILE"
			tmux kill-session -t "$SESSION_NAME"
		;;
		*)
			tmux send-keys -t "$SESSION_NAME:Manager.0" "/$input" ENTER;;
	esac
	history -s "$input"
done
