#!/usr/bin/env bash

SHELL=$(which bash)

ENABLE_PLAYIT="1"
export SERVER_BIN="/opt/vintagestory/VintagestoryServer"
export SESSION_NAME="VSServer"

export STATUS_FILE=$(mktemp)
export HISTORY="$(dirname "$0")/.history"

INHIBITOR_COMMAND="systemd-inhibit --what=idle --who='VintagestoryServer' --why='Server is running'"

# Pls don't touch
SERVER_COMMAND="$INHIBITOR_COMMAND '$SERVER_BIN' ; $(dirname "$0")/vss-exit"
CMD_COMMAND="
echo 'Commands entered here will be sent to server with / added at the beginning. «exit» will shut down the server.'
$(dirname "$0")/vss-cmd
"


# Kill session if exists and create it after
if (tmux ls | grep "$SESSION_NAME:"); then
	tmux kill-session -t "$SESSION_NAME"
fi

# Top panel
tmux new-session -d -s "$SESSION_NAME" -n Manager "$SERVER_COMMAND"
# Bottom panel
tmux split-window -t "$SESSION_NAME":Manager.0 -l 2 "$CMD_COMMAND"

if [ $ENABLE_PLAYIT = 1 ]; then
	# playit in another window
	tmux new-window -n playit -t "$SESSION_NAME" "playit"
	tmux select-window -t "$SESSION_NAME":Manager
fi

tmux attach -t "$SESSION_NAME"
